### ISSUE TITLE
Docker volumes

### ISSUE THREAD

**Issue by kroffske** [radames/Real-Time-Latent-Consistency-Model#31]
What is path to model folders? 
Is it possible to map volumes, so it wont download models every time?

**Comment by radames** [comment]
hi @Ravius ,

Since it used `diffusers` and `huggingface_hub`to download the models, the default place is [`HF_HOME`](https://huggingface.co/docs/huggingface_hub/v0.19.3/en/package_reference/environment_variables#hfhome) cache folder 
You can do this, set `HF_HOME=/data` then point your local cache or whatever folder you want

```bash
docker run -ti -p 7860:7860 -e HF_HOME=/data -v ~/.cache/huggingface:/data  --gpus all lcm-live 
```
