### ISSUE TITLE
Safety Checker for SDXL Turbo

### ISSUE THREAD

**Issue by acs107102** [radames/Real-Time-Latent-Consistency-Model#41]
Hello, I'm trying to use safety checker (--safe-checker True) for the StableDiffusionXLPipeline / StableDiffusionXLImg2ImgPipeline / StableDiffusionXLControlNetPipeline / StableDiffusionXLControlNetImg2ImgPipeline but it doesn't work for them. I just wondering if there's any other ways to avoid nsfw, thanks.

**Comment by radames** [comment]
Hi @acs107102,

I've updated all pipelines to use a unified safety checker. Since SDXL is relatively safer, Diffusers doesn't add a safety_checker on SD>2. Please let me know if it works now. Note that when NSFW content is detected, "None" is sent to the client. This freezes the live image rather than sending a black image, which could have a flickering effect.

```bash
python server/main.py --pipeline controlnetSDXLTurbo --safety-checker
```

**Comment by acs107102** [comment]
Hello, I tried the new code but it still provide NSFW image for controlnetSDXLTurbo.
